version: '3.5'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        environment: 
            NODE_ENV: production
            PORT: 3000
        networks:
            - public
            - private

    db:
        image: mongo
        networks:
            - private

networks:
    public:
    private: