# https://docs.docker.com/compose/extends/
#
# This file is automatically loaded via docker-compose. Set local dev-specific
# overrides for volumes and ports here.
#
# Strings and integers in this file replace those in docker-compose.yml
# Arrays in this file are merged/appended to those in docker-compose.yml
#
version: '3.5'
services:
    web:
        # command: ["npx", "gulp", "dev"]
        command: ["sh"]
        environment: 
            NODE_ENV: development
            SECRET: change-me
        volumes:
            - ./:/usr/src/app
        stdin_open: true
        tty: true
    db:
        ports:
            - "27017:27017"
        networks:
            - private
            - public